###
GET http://localhost:8081/api/v1/invoices
Authorization: Bearer N2MyMjEwOWU3OTc5YWQ0MGI5YzAyOTQ4ZTg1MGEwODM1NGMxYjAxNmViZDNmNTNlMmM2NTI4ZjM4NjYzZTA3ZmI5ZWY5MTYzNDA2MDhjZTNlZDMwODVmZTE3OTllNzEwOTE1MjU5ZTYzMWVhNTJmNjE2MTIyMTdmMTE4ZWZjMTA=
