apiVersion: v1
kind: Service
metadata:
  name: transaminvoice
  namespace: default
  labels:
    app: transaminvoice
spec:
  selector:
    app: transaminvoice
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8081
