apiVersion: v1
kind: Service
metadata:
  name: transamnotification
  namespace: default
  labels:
    app: transamnotification
spec:
  selector:
    app: transamnotification
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8082
