apiVersion: v1
kind: Service
metadata:
  name: transambackoffice
  namespace: default
  labels:
    app: transambackoffice
spec:
  selector:
    app: transambackoffice
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8081
