apiVersion: v1
kind: Service
metadata:
  name: transamstore
  namespace: default
  labels:
    app: transamstore
spec:
  selector:
    app: transamstore
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
