export enum DepartmentType {
  TICKETING = 'TICKETING',

  CONTROLLING = 'CONTROLLING',

  DRIVING = 'DRIVING',

  MAINTENANCE = 'MAINTENANCE',

  ACCOUNTING = 'ACCOUNTING',

  MARKETING = 'MARKETING',

  SALES = 'SALES',

  PROCUREMENT = 'PROCUREMENT',
}
